engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
    checks:
      squid:S1068: # unused private attribute, wrong detected for lombok generated classes
        enabled: false
  pmd:
    enabled: true
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
    config:
      file: "checkstyle.xml"
