spring:
  kafka:
    properties:
      bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration